package com.example.greathuman;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import com.example.greathuman.Adapters.descriptionAdapters;
import com.example.greathuman.Models.descriptionModel;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity {
    RecyclerView recyclerView;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        recyclerView = findViewById(R.id.rcv);

        ArrayList <descriptionModel> list = new ArrayList<>();
        list.add(new descriptionModel(R.drawable.abdulkalamprofile , "Abdul Kalam" , "Avul Pakir Jainulabdeen Abdul Kalam (/ˈəbdəl kəˈlɑːm/ (About this soundlisten); 15 October 1931 – 27 July 2015) was an Indian aerospace scientist who served as the 11th president of India from 2002 to 2007. He was born and raised in Rameswaram, Tamil Nadu and studied physics and aerospace engineering. He spent the next four decades as a scientist and science administrator, mainly at the Defence Research and Development Organisation (DRDO) and Indian Space Research Organisation (ISRO) and was intimately involved in India's civilian space programme and military missile development efforts.[1] He thus came to be known as the Missile Man of India for his work on the development of ballistic missile and launch vehicle technology.[2][3][4] He also played a pivotal organisational, technical, and political role in India's Pokhran-II nuclear tests in 1998, the first since the original nuclear test by India in 1974.[5]"));
        list.add(new descriptionModel(R.drawable.elon, "Elon Musk","Elon Reeve Musk FRS (/ˈiːlɒn/; born June 28, 1971) is an entrepreneur and business magnate. He is the founder, CEO, and Chief Engineer at SpaceX; early-stage investor, CEO, and Product Architect of Tesla, Inc.; founder of The Boring Company; and co-founder of Neuralink and OpenAI. A centibillionaire, Musk is the richest person in the world as of November 2021 with a net worth of around US$280 billion.[2]\n" +
                "\n" +
                "Musk was born to a Canadian mother and South African father and raised in Pretoria, South Africa. He briefly attended the University of Pretoria before moving to Canada at age 17 to attend Queen's University. He transferred to the University of Pennsylvania two years later, where he received bachelor's degrees in economics and physics. He moved to California in 1995 to attend Stanford University but decided instead to pursue a business career, co-founding the web software company Zip2 with brother Kimbal. The startup was acquired by Compaq for US$307 million in 1999. The same year, Musk co-founded online bank X.com, which merged with Confinity in 2000 to form PayPal. The company was bought by eBay in 2002 for $1.5 billion.\n" +
                "\n" +
                "In 2002, Musk founded SpaceX, an aerospace manufacturer and space transport services company, of which he is CEO and CTO. In 2004, he joined electric vehicle manufacturer Tesla Motors, Inc. (now Tesla, Inc.) as chairman and product architect, becoming its CEO in 2008. In 2006, he helped create SolarCity, a solar energy services company that was later acquired by Tesla and became Tesla Energy. In 2015, he co-founded OpenAI, a nonprofit research company that promotes friendly artificial intelligence. In 2016, he co-founded Neuralink, a neurotechnology company focused on developing brain–computer interfaces, and founded The Boring Company, a tunnel construction company. Musk has proposed the Hyperloop, a high-speed vactrain transportation system"));
        list.add(new descriptionModel(R.drawable.subhash , "Netaji", "Subhas Chandra Bose (/ʃʊbˈhɑːs ˈtʃʌndrə ˈboʊs/ (About this soundlisten) shuub-HAHSS CHUN-drə BOHSS;[11] 23 January 1897 – 18 August 1945)[12][h] was an Indian nationalist whose defiant patriotism made him a hero in India,[i][j][k] but whose attempt during World War II to rid India of British rule with the help of Nazi Germany and Imperial Japan left a troubled legacy.[l][m][n] The honorific Netaji (Hindustani: \"Respected Leader\"), first applied to Bose in Germany in early 1942 by the Indian soldiers of the Indische Legion and by the German and Indian officials in the Special Bureau for India in Berlin, was later used throughout India.[o]\n" +
                "\n" +
                "Bose had been a leader of the younger, radical, wing of the Indian National Congress in the late 1920s and 1930s, rising to become Congress President in 1938 and 1939.[p] However, he was ousted from Congress leadership positions in 1939 following differences with Mahatma Gandhi and the Congress high command.[20] He was subsequently placed under house arrest by the British before escaping from India in 1940.[21] Bose arrived in Germany in April 1941, where the leadership offered unexpected, if sometimes ambivalent, sympathy for the cause of India's independence, contrasting starkly with its attitudes towards other colonised peoples and ethnic communities.[22][23] In November 1941, with German funds, a Free India Centre was set up in Berlin, and soon a Free India Radio, on which Bose broadcast nightly. A 3,000-strong Free India Legion, comprising Indians captured by Erwin Rommel's Afrika Korps, was also formed to aid in a possible future German land invasion of India.[24] By spring 1942, in light of Japanese victories in southeast Asia and changing German priorities, a German invasion of India became untenable, and Bose became keen to move to southeast Asia.[25] Adolf Hitler, during his only meeting with Bose in late May 1942, suggested the same, and offered to arrange for a submarine.[26] During this time Bose also became a father; his wife, [5] or companion,[q] Emilie Schenkl, whom he had met in 1934, gave birth to a baby girl in November 1942.[5][22] Identifying strongly with the Axis powers, and no longer apologetically, Bose boarded a German submarine in February 1943.[27][28] Off Madagascar, he was transferred to a Japanese submarine from which he disembarked in Japanese-held Sumatra in May 1943."));
        list.add(new descriptionModel(R.drawable.rohits , "Rohit Sharma" , "Rohit Gurunath Sharma (born 30 April 1987) is an Indian international cricketer who captains the India national cricket team in T20Is. He also plays for Mumbai in domestic cricket and captains Mumbai Indians in the Indian Premier League as a right-handed batsman and an occasional right-arm off break bowler. He is the vice-captain of the Indian national team in ODIs. He is widely regarded as one of the best openers of all time.[1][2][3]\n" +
                "\n" +
                "Outside cricket, Sharma is an active supporter of animal welfare campaigns. He is the official Rhino Ambassador for WWF-India and is a member of People for the Ethical Treatment of Animals (PETA). He has worked with PETA in its campaign to raise awareness of the plight of homeless cats and dogs in India."));
        list.add(new descriptionModel(R.drawable.virat , "Virat Kohli","Virat Kohli (Hindustani: [ʋɪˈɾɑːʈ ˈkoːɦliː] (About this soundlisten); born 5 November 1988) is an Indian cricketer and captain of India national cricket team in ODIs and Tests .[2] He plays for Delhi in domestic cricket and Royal Challengers Bangalore in the Indian Premier League as a right-handed batsman. Kohli is considered as one of the best batsmen of his era.[3]\n" +
                "\n" +
                "Kohli made his Test debut in 2011[4] He reached the number one spot in the ICC rankings for ODI batsmen for the first time in 2013.[5] He has won Man of the Tournament twice at the ICC World Twenty20 (in 2014 and 2016). He also holds the world record of being the fastest to 23,000 international runs.[6]\n" +
                "\n" +
                "Kohli has been the recipient of many awards– most notably the Sir Garfield Sobers Trophy (ICC Men's Cricketer of the Decade): 2011–2020; Sir Garfield Sobers Trophy (ICC Cricketer of the Year) in 2017 and 2018; ICC Test Player of the Year (2018); ICC ODI Player of the Year (2012, 2017, 2018) and Wisden Leading Cricketer in the World (2016, 2017 and 2018).[7] At the national level, he was awarded the Arjuna Award in 2013, the Padma Shri under the sports category in 2017[8] and the Rajiv Gandhi Khel Ratna award, the highest sporting honour in India, in 2018.[9] He is ranked as one of the world's most famous athletes by ESPN[10] and one of the most valuable athlete brands by Forbes.[11] In 2018, Time magazine named him one of the 100 most influential people in the world.[12] In 2020, he was ranked 66th in Forbes list of the top 100 highest-paid athletes in the world for the year 2020 with estimated earnings of over $26 million.[13]"));
        list.add(new descriptionModel(R.drawable.vivekaanda , "Swami Vivekanand","Swami Vivekananda (/ˈswɑːmi ˌvɪveɪˈkɑːnəndə/; Bengali: [ʃami bibekanɔndo] (About this soundlisten); 12 January 1863 – 4 July 1902), born Narendranath Datta (Bengali: [nɔrendronatʰ dɔto]), was an Indian Hindu monk. He was a chief disciple of the 19th-century Indian mystic Ramakrishna.[4][5] Influenced by Western esotericism,[6][7][8] he was a key figure in the introduction of the Indian darsanas (teachings, practices) of Vedanta and Yoga to the Western world,[9][10][11] and is credited with raising interfaith awareness, bringing Hinduism to the status of a major world religion during the late 19th century.[12] He was a major force in the contemporary Hindu reform movements in India, and contributed to the concept of nationalism in colonial India.[13] Vivekananda founded the Ramakrishna Math and the Ramakrishna Mission.[10] He is perhaps best known for his speech which began with the words \"Sisters and brothers of America ...,\"[14] in which he introduced Hinduism at the Parliament of the World's Religions in Chicago in 1893."));
        list.add(new descriptionModel(R.drawable.prabhupad, "Srila Prabhupada", "Abhay Charanaravinda Bhaktivedanta Swami (IAST: Abhaya Caraṇāravinda Bhakti-vedānta Svāmī; 1 September 1896 – 14 November 1977[2]) or Srila Prabhupada, born Abhay Charan De, was an Indian spiritual teacher and the founder-acharya (preceptor) of the International Society for Krishna Consciousness (ISKCON),[3] commonly known as the \"Hare Krishna movement\".[1][4][5][6][7] Members of the ISKCON movement view Bhaktivedanta Swami as a representative and messenger of Krishna Chaitanya.[8]\n" +
                "\n" +
                "Born in an aristocratic Subarna Banik[9] family in Kolkata (then called Calcutta), he was educated at the Scottish Church College there.[1] Before adopting the life of a novice renunciate (vanaprastha) in 1950,[10] he was married with children and owned a small pharmaceutical business.[11][12] In 1959, he took a vow of renunciation (sannyasa) and started writing commentaries on Vaishnava scriptures.[13] In his later years, as a travelling Vaishnava monk, he became an influential communicator of Gaudiya Vaishnava sampradaya's theology to India and specifically to the West through his leadership of ISKCON, founded in 1966.[14][15] As the founder of ISKCON, he \"emerged as a major figure of the Western counterculture, initiating thousands of young Americans.\"[16] He was criticized by anti-cult groups, but was well regarded by religious scholars, such as J. Stillson Judah, Harvey Cox, Larry Shinn and Thomas Hopkins, who praised Bhaktivedānta Swāmi's translations and defended the group against distorted media images and misinterpretations.[17] Religious leaders from other Gaudiya Vaishnava institutions also gave him credit for his achievements."));
        list.add(new descriptionModel(R.drawable.kunal , "Kunal Shah","Kunal Shah is an Indian entrepreneur and venture capitalist who is the founder of CRED, which is considered the second-fastest-growing unicorn startup in India. In 2021, this startup was slated to hit a $2 billion valuation with $200 million funding."));
        list.add(new descriptionModel(R.drawable.tinamam , "Tina Dabi","IAS OFFICER"));
        list.add(new descriptionModel(R.drawable.food , "Samosa","A samosa (/səˈmoʊsə/) is a South Asian[2] fried or baked pastry with a savory filling like spiced potatoes, onions, peas, chicken and other meats, or lentils. It may take different forms, including triangular, cone, or half-moon shapes, depending on the region.[3][4][5] Samosas are often accompanied by chutney, and have origins in medieval times or earlier.[3] Samosas are a popular entrée, appetizer, or snack in the local cuisines of South Asia. Due to emigration and cultural diffusion from these areas, samosas today are often prepared in other regions."));

        descriptionAdapters adapter = new descriptionAdapters(list,this);
        recyclerView.setAdapter(adapter);

        LinearLayoutManager layoutManager = new LinearLayoutManager(this , LinearLayoutManager.VERTICAL,false);
        recyclerView.setLayoutManager(layoutManager);


    }
}